<?php

namespace app\models\forms;

use yii\base\Model;
use Yii;
use yii\web\UploadedFile;

class OrderForm extends Model
{

    public $user_id;
    public $fullname;
    public $country;
    public $birth_date;
    public $phone;
    public $order;
    public $product_id;
    public $city;
    public $zip_code;
    public $whatsapp;
    public $status;

    private $_oldAttributes = [];

    public function rules() {
        return [
            [['fullname', 'country', 'birth_date', 'phone'], 'required'],
            [['order', 'product_id', 'city', 'zip_code', 'whatsapp', 'status', 'user_id'], 'safe'],
        ];
    }

    public function attributeLabels() {
        return [
            'fullname'             => Yii::t('site', 'Full name'),
            'country'               => Yii::t('site', 'Country'),
            'birth_date'            => Yii::t('site', 'Birth date'),
            'phone'                 => Yii::t('site', 'Phone'),
            'order' => 'Заказ',
            'product_id' => 'Товар',
            'city' => 'Город',
            'zip_code' => 'Индекс',
            'whatsapp' => 'WhatsApp',
            'status' => 'Статус',
        ];
    }

    public function __construct($config = []) {
        $user = Yii::$app->user->identity;
        $this->setAttributes($user->getAttributes());
        parent::__construct($config);
    }

    public function setAttributes($values, $safeOnly = true) {
        if(empty($this->_oldAttributes)){
            $this->_oldAttributes = $this->attributes;
        }
        parent::setAttributes($values, $safeOnly); // TODO: Change the autogenerated stub
    }

    public function save() {
        $order = new \app\models\EmeraldOrder();
        $order->id_user = $this->id_user;
        $order->fullname = $this->fullname;
        $order->country = $this->country;
        $order->birth_date = $this->birth_date;
        $order->phone = $this->phone;
        $order->order = 'Пластырь';
        $order->product_id = 1;
        $order->city = $this->city;
        $order->zip_code = $this->zip_code;
        $order->whatsapp = $this->whatsapp;
        $order->status = $this->status;
        if ($order->save) return true;

        return false;
    }
}